import { LENSES, SIGNAL_IDS } from "@aeo/scoring";
import type { AuditReport } from "@/lib/audit/types";
import { buildFaqJsonLd } from "@/lib/audit/jsonld";
import { SIGNAL_META } from "@/lib/audit/signalMeta";

export interface AuditExportBundle {
  markdown: string;
  html: string;
  jsonLd: string | null;
  scoresJson: string;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  })[character] ?? character);
}

function safeJsonLd(value: string): string {
  return value.replace(/</g, "\\u003c");
}

export function buildAuditMarkdown(report: AuditReport): string {
  const lensRows = LENSES.map((lens) => {
    const result = report.scores.lenses[lens];
    return `| ${lens === "aiOverview" ? "AI Overview" : lens.toUpperCase()} | ${result.score}/100 | ${result.capped ? "Yes" : "No"} |`;
  });
  const weakSignals = SIGNAL_IDS
    .map((id) => ({ id, result: report.scores.signals[id] }))
    .filter(({ result }) => result.score < 70)
    .sort((a, b) => a.result.score - b.result.score)
    .map(({ id, result }) => `- [ ] **${SIGNAL_META[id].label} (${id})** — ${result.score}/100. ${SIGNAL_META[id].blurb}`);
  const findings = [
    ...report.findings.blockers.map((item) => `- **Blocker:** ${item.issue}${item.location ? ` — ${item.location}` : ""}`),
    ...report.findings.questionGaps.map((item) => `- **Question gap:** ${item}`),
    ...report.findings.anchorSuggestions.map((item) => `- **Citation:** ${item.claim} — suggested source: ${item.suggestedSourceType}`),
  ];
  const rewrites = (report.rewrites?.hunks ?? []).flatMap((hunk) => [
    `### ${hunk.label}`,
    "",
    "**Before**",
    "",
    hunk.before,
    "",
    "**After**",
    "",
    hunk.after,
    "",
  ]);

  return [
    `# AI-search audit: ${report.page.title || report.page.finalUrl}`,
    "",
    `- URL: ${report.page.finalUrl}`,
    `- Audited: ${report.page.fetchedAt}`,
    `- Word count: ${report.page.wordCount}`,
    `- Model: ${report.scores.modelId}`,
    "",
    "## Scores",
    "",
    "| Lens | Score | Capped |",
    "| --- | ---: | :---: |",
    ...lensRows,
    "",
    "## Findings",
    "",
    ...(findings.length ? findings : ["No priority findings were returned."]),
    "",
    "## Optimization roadmap",
    "",
    ...(weakSignals.length ? weakSignals : ["All signals scored 70 or above."]),
    "",
    "## Suggested rewrites",
    "",
    ...(rewrites.length ? rewrites : ["No rewrites were returned.", ""]),
    "---",
    "Generated by SEO AI Audit. Re-run the source URL before publishing decisions based on this report.",
    "",
  ].join("\n");
}

export function buildAuditExportBundle(report: AuditReport): AuditExportBundle {
  const markdown = buildAuditMarkdown(report);
  const jsonLd = buildFaqJsonLd(report.findings.qaPairs);
  const title = escapeHtml(report.page.title || "AI-search audit");
  const htmlBody = markdown
    .split("\n")
    .map((line) => `<p>${escapeHtml(line)}</p>`)
    .join("\n");
  const schema = jsonLd ? `\n<script type="application/ld+json">\n${safeJsonLd(jsonLd)}\n</script>` : "";
  const html = `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8" />\n<meta name="viewport" content="width=device-width, initial-scale=1" />\n<title>${title}</title>${schema}\n<style>body{font:16px/1.6 system-ui,sans-serif;max-width:900px;margin:40px auto;padding:0 20px;color:#171717}p{margin:.35rem 0;white-space:pre-wrap}</style>\n</head>\n<body>\n<main>${htmlBody}</main>\n</body>\n</html>\n`;
  return { markdown, html, jsonLd, scoresJson: JSON.stringify(report.scores, null, 2) };
}
