import { LENSES, SIGNAL_IDS } from "@aeo/scoring";
import type { AuditReport } from "@/lib/audit/types";
import { buildFaqJsonLd } from "@/lib/audit/jsonld";
import { SIGNAL_META } from "@/lib/audit/signalMeta";

export interface AuditExportBundle {
  markdown: string;
  html: string;
  jsonLd: string | null;
  scoresJson: string;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  })[character] ?? character);
}

function safeJsonLd(value: string): string {
  return value.replace(/</g, "\\u003c");
}

export function buildAuditMarkdown(report: AuditReport): string {
  const lensRows = LENSES.map((lens) => {
    const result = report.scores.lenses[lens];
    return `| ${lens === "aiOverview" ? "AI Overview" : lens.toUpperCase()} | ${result.score}/100 | ${result.capped ? "Yes" : "No"} |`;
  });
  const weakSignals = SIGNAL_IDS
    .map((id) => ({ id, result: report.scores.signals[id] }))
    .filter(({ result }) => result.score < 70)
    .sort((a, b) => a.result.score - b.result.score)
    .map(({ id, result }) => `- [ ] **${SIGNAL_META[id].label} (${id})** — ${result.score}/100. ${SIGNAL_META[id].blurb}`);
  const findings = [
    ...report.findings.blockers.map((item) => `- **Blocker:** ${item.issue}${item.location ? ` — ${item.location}` : ""}`),
    ...report.findings.questionGaps.map((item) => `- **Question gap:** ${item}`),
    ...report.findings.anchorSuggestions.map((item) => `- **Citation:** ${item.claim} — suggested source: ${item.suggestedSourceType}`),
  ];
  const rewrites = (report.rewrites?.hunks ?? []).flatMap((hunk) => [
    `### ${hunk.label}`,
    "",
    "**Before**",
    "",
    hunk.before,
    "",
    "**After**",
    "",
    hunk.after,
    "",
  ]);

  return [
    `# AI-search audit: ${report.page.title || report.page.finalUrl}`,
    "",
    `- URL: ${report.page.finalUrl}`,
    `- Audited: ${report.page.fetchedAt}`,
    `- Word count: ${report.page.wordCount}`,
    `- Model: ${report.scores.modelId}`,
    "",
    "## Scores",
    "",
    "| Lens | Score | Capped |",
    "| --- | ---: | :---: |",
    ...lensRows,
    "",
    "## Findings",
    "",
    ...(findings.length ? findings : ["No priority findings were returned."]),
    "",
    "## Optimization roadmap",
    "",
    ...(weakSignals.length ? weakSignals : ["All signals scored 70 or above."]),
    "",
    "## Suggested rewrites",
    "",
    ...(rewrites.length ? rewrites : ["No rewrites were returned.", ""]),
    "---",
    "Generated by SEO AI Audit. Re-run the source URL before publishing decisions based on this report.",
    "",
  ].join("\n");
}

function buildAuditHtml(report: AuditReport, jsonLd: string | null): string {
  const lensRows = LENSES.map((lens) => {
    const result = report.scores.lenses[lens];
    const name = lens === "aiOverview" ? "AI Overview" : lens.toUpperCase();
    return `<tr><th scope="row">${name}</th><td>${result.score}/100</td><td>${result.capped ? "Yes" : "No"}</td></tr>`;
  }).join("");
  const findingItems = [
    ...report.findings.blockers.map((item) => `<li><strong>Blocker:</strong> ${escapeHtml(item.issue)}${item.location ? ` — ${escapeHtml(item.location)}` : ""}</li>`),
    ...report.findings.questionGaps.map((item) => `<li><strong>Question gap:</strong> ${escapeHtml(item)}</li>`),
    ...report.findings.anchorSuggestions.map((item) => `<li><strong>Citation:</strong> ${escapeHtml(item.claim)} — suggested source: ${escapeHtml(item.suggestedSourceType)}</li>`),
  ].join("");
  const roadmapItems = SIGNAL_IDS
    .map((id) => ({ id, result: report.scores.signals[id] }))
    .filter(({ result }) => result.score < 70)
    .sort((a, b) => a.result.score - b.result.score)
    .map(({ id, result }) => `<li><strong>${escapeHtml(SIGNAL_META[id].label)} (${id})</strong> — ${result.score}/100. ${escapeHtml(SIGNAL_META[id].blurb)}</li>`)
    .join("");
  const rewriteItems = (report.rewrites?.hunks ?? []).map((hunk) => `
    <article><h3>${escapeHtml(hunk.label)}</h3><h4>Before</h4><p>${escapeHtml(hunk.before)}</p><h4>After</h4><p>${escapeHtml(hunk.after)}</p></article>`).join("");
  const schema = jsonLd ? `\n<script type="application/ld+json">\n${safeJsonLd(jsonLd)}\n</script>` : "";
  const title = escapeHtml(report.page.title || "AI-search audit");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>${schema}
<style>body{font:16px/1.6 system-ui,sans-serif;max-width:900px;margin:40px auto;padding:0 20px;color:#171717}table{width:100%;border-collapse:collapse}th,td{padding:8px;border:1px solid #ccc;text-align:left}article{border-top:1px solid #ccc;margin-top:24px}code{overflow-wrap:anywhere}</style>
</head>
<body>
<main>
<h1>AI-search audit: ${title}</h1>
<dl><dt>URL</dt><dd><code>${escapeHtml(report.page.finalUrl)}</code></dd><dt>Audited</dt><dd>${escapeHtml(report.page.fetchedAt)}</dd><dt>Word count</dt><dd>${report.page.wordCount}</dd><dt>Model</dt><dd>${escapeHtml(report.scores.modelId)}</dd></dl>
<section><h2>Scores</h2><table><thead><tr><th>Lens</th><th>Score</th><th>Capped</th></tr></thead><tbody>${lensRows}</tbody></table></section>
<section><h2>Findings</h2>${findingItems ? `<ul>${findingItems}</ul>` : "<p>No priority findings were returned.</p>"}</section>
<section><h2>Optimization roadmap</h2>${roadmapItems ? `<ul>${roadmapItems}</ul>` : "<p>All signals scored 70 or above.</p>"}</section>
<section><h2>Suggested rewrites</h2>${rewriteItems || "<p>No rewrites were returned.</p>"}</section>
</main>
</body>
</html>
`;
}

export function buildAuditExportBundle(report: AuditReport): AuditExportBundle {
  const markdown = buildAuditMarkdown(report);
  const jsonLd = buildFaqJsonLd(report.findings.qaPairs);
  const html = buildAuditHtml(report, jsonLd);
  return { markdown, html, jsonLd, scoresJson: JSON.stringify(report.scores, null, 2) };
}
